version: "3"

services:
  db:
    image: postgres:10.4
    environment:
      DB_NAME: taskmanager
      POSTGRES_DB: taskmanager
      POSTGRES_USER: taskmanager
      POSTGRES_PASSWORD: password
    ports:
    - 5432:5432
  taskmanager:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskmanager
      DB_USER: taskmanager
      DB_PASSWORD: password
    volumes:
      - "./:/usr/src"
    working_dir: /usr/src
    depends_on:
      - db
    command: yarn start
    ports:
      - 3000:3000
      - 9220:9220
  redoc:
    image: redocly/redoc
    ports:
      - "8081:1234"
    environment:
      SPEC_URL: swagger.yml
      PORT: 1234
    volumes:
      - ./swagger.yml:/usr/share/nginx/html/swagger.yml

volumes:
  yarn:
  build:
  node-modules:
